from .level_type_controller import level_type_route
from .colaborator_type_controller import colaborator_type_route
from .colaborator_controller import colaborator_route
from .student_controller import student_route
from .group_controller import group_route
from .group_schedule_controller import group_schedule_route
from .group_student_controller import group_student_route
from .group_colaborator_controller import group_colaborator_route
