"""Add colaborator_type on Colaborator

Revision ID: 690fd99542d7
Revises: 984fe64887c7
Create Date: 2023-04-19 17:32:40.199707

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from src.domain.enums.status_enum import StatusEnum

from src.infra.adapters.orm.database_schema import StatusType

# revision identifiers, used by Alembic.
revision = '690fd99542d7'
down_revision = '984fe64887c7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('GroupSchedule',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('status', StatusType(StatusEnum), nullable=False),
    sa.Column('team_id', sa.BigInteger(), nullable=False),
    sa.Column('day_week', sa.Integer(), nullable=False),
    sa.Column('hour_day', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['Group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('TeamSchedule')
    op.add_column('Colaborator', sa.Column('colaborator_type_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Colaborator', 'ColaboratorType', ['colaborator_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Colaborator', type_='foreignkey')
    op.drop_column('Colaborator', 'colaborator_type_id')
    op.create_table('TeamSchedule',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('team_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('day_week', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('hour_day', mysql.TIME(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['Group.id'], name='TeamSchedule_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='latin1_general_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_table('GroupSchedule')
    # ### end Alembic commands ###
