"""Primeira versao

Revision ID: 984fe64887c7
Revises: 

Create Date: 2023-04-08 15:34:32.128600



"""

from alembic import op

import sqlalchemy as sa
from src.infra.adapters.orm.database_schema import *



# revision identifiers, used by Alembic.
revision = '984fe64887c7'
down_revision = None

branch_labels = None

depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('Colaborator',

    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', StatusType(), nullable=False),
    sa.Column('cpf', CpfType(length=11), nullable=False),
    sa.Column('email', EmailType(length=100), nullable=False),
    sa.Column('name', NameType(length=100), nullable=False),

    sa.Column('cell_phone', CellPhoneType(length=11), nullable=False),

    sa.Column('cell_phone2', CellPhoneType(length=11), nullable=True),

    sa.PrimaryKeyConstraint('id')

    )

    op.create_table('ColaboratorType',

    sa.Column('id', sa.Integer(), nullable=False),

    sa.Column('status', StatusType(), nullable=False),
    sa.Column('description', DescriptionType(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('LevelType',

    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', StatusType(), nullable=False),
    sa.Column('description', DescriptionType(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', StatusType(), nullable=False),

    sa.Column('cpf', CpfType(length=11), nullable=False),
    sa.Column('email', EmailType(length=100), nullable=False),
    sa.Column('name', NameType(length=100), nullable=False),
    sa.Column('cell_phone', CellPhoneType(length=11), nullable=False),
    sa.Column('cell_phone2', CellPhoneType(length=11), nullable=True),
    sa.Column('situation', StudentSituationType(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Group',
    sa.Column('id', sa.BigInteger(), nullable=False),

    sa.Column('status', StatusType(), nullable=False),
    sa.Column('max_students', sa.Integer(), nullable=False),
    sa.Column('level_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['level_type_id'], ['LevelType.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('GroupColaborator',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('status', StatusType(), nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),

    sa.Column('colaborator_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['colaborator_id'], ['Colaborator.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['Group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('GroupStudent',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('status', StatusType(), nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['Group.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['Student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('TeamSchedule',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('status', StatusType(), nullable=False),
    sa.Column('team_id', sa.BigInteger(), nullable=False),
    sa.Column('day_week', sa.Integer(), nullable=False),
    sa.Column('hour_day', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['Group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TeamSchedule')
    op.drop_table('GroupStudent')
    op.drop_table('GroupColaborator')
    op.drop_table('Group')
    op.drop_table('Student')
    op.drop_table('LevelType')
    op.drop_table('ColaboratorType')
    op.drop_table('Colaborator')
    # ### end Alembic commands ###
